apiVersion: apps/v1
kind: Deployment
metadata:
  name: mystnodes
  namespace: myst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mystnodes
  template:
    metadata:
      labels:
        app: mystnodes
    spec:
      containers:
        - name: mystnodes
          image: docker.io/mysteriumnetwork/myst:latest
          ports:
            - containerPort: 4449
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command:
            [
              "/usr/local/bin/docker-entrypoint.sh",
              "service",
              "--agreed-terms-and-conditions",
            ]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: mystnodes-pvc
              mountPath: /var/lib/mysterium-node
      hostNetwork: true
      volumes:
        - name: mystnodes-pvc
          persistentVolumeClaim:
            claimName: mystnodes-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mystnodes-pvc
  namespace: myst
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mystnodes-svc
  namespace: myst
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 4449
  selector:
    app: mystnodes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mystnodes-ingress
  namespace: myst
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: mystnodes-ipwhitelist@kubernetescrd # Only if you only want local addresses then go to the dashboard
spec:
  tls:
    - hosts:
        - your domain name
      secretName: mystnodes-tls
  rules:
    - host: your domain name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mystnodes-svc
                port:
                  number: 80
---
# Only if you only want local addresses then go to the dashboard
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mystnodes-ipwhitelist
  namespace: myst
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.0.0/16  # Replace with your network's local IP range
      - 192.168.1.0/24  # Replace with your network's local IP range
      - 127.0.0.1/32    # Allows access from localhost